plugins {
    id 'com.android.application'
}

android {
    namespace 'com.financasdecasa.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.financasdecasa.app"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "0.1.0-beta"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
